require:
  - rubocop-rspec
  - rubocop-rails  

AllCops:
  Exclude:
    - "vendor/**/*" # rubocop config/default.yml
    - "db/schema.rb"
    - "docs/**/*"
    - "bin/**/*"
  DisplayCopNames: true

Style/Documentation:
  Enabled: false

Style/PreferredHashMethods:
  Enabled: false

Style/Lambda:
  Enabled: false

Rails/FilePath: 
  Enabled: false

RSpec/FilePath: 
  Enabled: false
RSpec/NamedSubject:
  Enabled: false  
RSpec/ContextWording:
  Enabled: false   

#テストは現時点では書かない場合にxcontextなどをするので、それを許可する 
RSpec/EmptyExampleGroup: 
  Enabled: false   

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/environments/*'    
    - lib/tasks/auto_annotate_models.rake 

Metrics:
  Exclude:
      - 'db/migrate/*'      

Style/AsciiComments:
  Enabled: false

# 一つのテスト内で少数なら一度に確認するのは問題ない
RSpec/MultipleExpectations:
  Max: 3

# テストで実行結果を確認するための処理をしているとデフォルトだと厳しすぎる
RSpec/ExampleLength:
  Max: 10  

Naming/PredicateName:
  Enabled: false