require:
  - rubocop-rspec
  - rubocop-rails  

AllCops:
  Exclude:
    - "vendor/**/*" # rubocop config/default.yml
    - "db/schema.rb"
    - "docs/**/*"
    - "bin/**/*"
  DisplayCopNames: true

Style/Documentation:
  Enabled: false

Style/PreferredHashMethods:
  Enabled: false

Style/Lambda:
  Enabled: false

Rails/FilePath: 
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/environments/*'

  