openapi: 3.1.0
info:
  title: zombie_sns
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /players:
    parameters: []
    post:
      summary: Players SignUp
      operationId: post-users-userId
      responses:
        '200':
          description: 正しく作成できた場合
          content:
            application/json:
              schema:
                $ref: ../models/Player.yaml
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: 鈴木太郎
                age:
                  type: number
                  minimum: 18
                  maximum: 65
                inventory:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        $ref: ../models/ItemName.yaml
                      count:
                        type: integer
                        example: 1
            examples:
              example:
                value:
                  name: 鈴木太郎
                  age: 18
                  inventory:
                    - name: Fiji Water
                      count: 1
        description: ''
  '/players/{player_id}/inventory':
    put:
      summary: ExchangeItems
      operationId: put-players-inventory
      responses:
        '200':
          description: 交換に成功した
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum:
                      - success
                    example: success
              examples:
                example-1:
                  value:
                    status: success
        '400':
          description: |
            以下の場合にエラーになる
            ＊指定したプレイヤーが生存者ではなくゾンビ等の場合
            ＊交換するアイテム分のポイントが等しくないない場合
            ＊パートナーが生存していない場合
            ＊交換しようとしたアイテムが存在しない場合
          content:
            application/json:
              schema:
                $ref: ../models/Error.yaml
              examples:
                example(文言は例):
                  value:
                    - 存在しないプレイヤーと交換しようとしました
      description: していした生存者とアイテムを交換する
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                partner_player_id:
                  type: number
                  example: 2
                requeser_items:
                  type: array
                  description: ''
                  items:
                    type: object
                    properties:
                      name:
                        $ref: ../models/ItemName.yaml
                      count:
                        type: integer
                        example: 1
                partner_items:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        $ref: ../models/ItemName.yaml
                      count:
                        type: integer
                        example: 2
            examples:
              example-1:
                value:
                  partner_player_id: 2
                  requeser_items:
                    - name: Fiji Water
                      count: 1
                  partner_items:
                    - name: Fiji Water
                      count: 2
      parameters: []
    parameters:
      - schema:
          type: string
        name: player_id
        in: path
        required: true
  /filed/current_location:
    put:
      summary: Player Move Whereabouts
      operationId: put-players-current_location
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    player_id:
                      type: integer
                    location:
                      $ref: ../models/Location.yaml
    parameters: []
  /filed/infection:
    parameters: []
    put:
      summary: Report Infection
      operationId: put-players-player_id-status
      responses:
        '200':
          description: 報告に成功した場合
          content:
            application/json:
              schema:
                type: object
                properties:
                  reporting_target_player_id:
                    type: number
                  counting_to_become_zombie:
                    type: number
        '':
          content:
            application/json:
              schema:
                type: object
                properties:
                  zombie_player_ids:
                    type: array
                    items:
                      type: number
      description: 全プレイヤーが感染していないかを確認する
      requestBody:
        content:
          application/json:
            schema:
              type: object
  /filed:
    get:
      summary: Creating Report
      operationId: post-report
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  zombie_percentage:
                    type: number
                    format: float
                    description: サインアップした人の中でゾンビになった割合
                  survivor_percentage:
                    type: number
                    description: サインアップした人の中でゾンビになった割合
                  average_amount_of_each_item_possessed:
                    type: number
                    description: 各アイテムの全生存者が持っている個数の平均
                  points_wasted:
                    type: integer
                    description: ゾンビになったり、死亡したりしたひとが持っていたアイテムのポイント
              examples:
                example-1:
                  value:
                    zombie_percentage: -3.402823669209385e+38
                    survivor_percentage: 0
                    average_amount_of_each_item_possessed: 0
                    points_wasted: 0
      description: ''
    parameters: []
