@startuml robustness

left to right direction

actor 生存者
entity フィールド
entity イベントリ
entity アイテム
actor 感染者
actor 管理者

イベントリ --> アイテム

package "新規ユーザーコンテキスト"{
    control 登録する    
    actor 新規ユーザー
    
    新規ユーザー --> 登録する
    登録する --> イベントリ
    登録する -> 生存者
}

package "生存者コンテキスト"{
    control アイテムの交換
    control 感染報告
    control 移動する
    control 感染の確定
    
    entity 現在地
    entity 別の生存者のイベントリ    
    actor 別の生存者

    生存者 --> アイテムの交換
    アイテムの交換 --> イベントリ
    アイテムの交換 --> 別の生存者
    別の生存者 --> 別の生存者のイベントリ
    生存者 --> 移動する
    移動する --> 現在地
    生存者 --> 感染報告
    感染報告 --> 別の生存者
    別の生存者 --> 感染の確定
    感染の確定 --> 感染者
}

package "レポートコンテキスト"{

    control 感染した生存者の割合の計算
    control 感染していない生存者の割合の計算
    control 生存者の各アイテムの平均所持量の計算
    control 感染した生存者のために失われたポイントの計算
    control レポートの作成

    entity レポート
    
    actor 別の生存者

    管理者 --> レポートの作成
    レポートの作成 --> 感染した生存者の割合の計算    
    感染した生存者の割合の計算 --> 感染者
    レポートの作成 --> 感染していない生存者の割合の計算
    感染していない生存者の割合の計算 --> 生存者
    レポートの作成 --> 生存者の各アイテムの平均所持量の計算
    生存者の各アイテムの平均所持量の計算 --> 生存者
    レポートの作成 --> 感染した生存者のために失われたポイントの計算
    感染した生存者のために失われたポイントの計算 --> 感染者
    レポートの作成 --> レポート
}

@enduml