@startuml robustness

left to right direction

actor 生存者
entity フィールド
entity イベントリ
entity アイテム
actor 感染者
actor 管理者

イベントリ --> アイテム

package "新規ユーザーコンテキスト"{
    control 登録する    
    actor 新規ユーザー
    
    新規ユーザー --> 登録する
    登録する --> イベントリ
    登録する -> 生存者
}

package "生存者コンテキスト"{
    control アイテムの交換
    
    entity 現在地
    entity 別の生存者のイベントリ    
    actor 別の生存者

    生存者 --> アイテムの交換
    アイテムの交換 --> イベントリ
    アイテムの交換 --> 別の生存者
    別の生存者 --> 別の生存者のイベントリ    
}

package "感染者コンテキスト"{
    control 感染しきる
    control 襲う
    
    entity 現在地
    entity 別の生存者のイベントリ    
    
    actor ゾンビ
    actor 死亡者

    感染者 --> 感染しきる
    感染しきる --> ゾンビ
    ゾンビ --> 襲う
    襲う --> 死亡者
}

package "フィールドコンテキスト"{

    control 現在のフィールドの状況のレポート作成
    control 感染を拡大させる
    control 移動させる
    
    entity レポート    

    管理者 --> 現在のフィールドの状況のレポート作成
    現在のフィールドの状況のレポート作成 --> レポート
    フィールド --> 感染を拡大させる
    感染を拡大させる --> 感染者
    フィールド --> 移動させる
    移動させる --> 生存者
}

@enduml